version: "3"

services:
    postgis:
        image: "postgres:9.6"
        hostname: openclinicadb
        domainname: tlclinic.com
        volumes:
            - "ocdb-data:/var/lib/postgresql/data:rw"
            - "$PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=password"
            - "POSTGRES_INITDB_ARGS=\"-E 'UTF-8' --locale=POSIX\""
            - "LANG=en_US.utf8"
            - "PGDATA=/var/lib/postgresql/data"
        restart: "on-failure:5"

    pgadmin:
        image: "dpage/pgadmin4:4.5"
        hostname: pgadmin
        domainname: tlclinic.com
        ports:
          - "10080:80"
          - "443:443"
        environment:
          - "PGADMIN_DEFAULT_EMAIL=user@example.com"
          - "PGADMIN_DEFAULT_PASSWORD=password"
          - "LANG=C.UTF-8"
          - "GPG_KEY=key"
        restart: "on-failure:5"
    
    openclinica:
      image:  "tlclinic2020/openclinica:3.15"
      hostname: openclinicaportal
      domainname: tlclinic.com
      volumes:
        - "oc-data:/usr/local/tomcat/openclinica.data"
      ports:
        - 80:8080
      environment:
        - "LOG_LEVEL=INFO"
        - "TZ=UTC"
        - "DB_TYPE=postgres"
        - "DB_HOST=openclinicadb"
        - "DB_NAME=openclinica"
        - "DB_USER=clinica"
        - "DB_PASS=clinica"
        - "DB_PORT=5432"
        - "SUPPORT_URL=\"https://www.openclinica.com/community-edition-open-source-edc/\""
